Fix renamed ResponseClass in ChargeRequest
Issue: PaymentsSimulator (test mode) is not working. Exception is thrown:

```
Error: Class `Omnipay\ComfortPay\Message\ChargeResponse` not found
```

Fix: Two `ChargeResponse` occurences renamed to `CardTransactionResponse`
in test mode block within `Omnipay\ComfortPay\Message\ChargeRequest`.